apiVersion: v1
kind: PersistentVolume
metadata:
  name: html-hello-maciej-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp/pv
    server: 172.17.0.2
